question_data = [
    {'text': 'The music group Daft Punk got their name from a negative review they recieved.', 'answer': 'TRUE'},
    {'text': 'There are no roads in/out of Juneau, Alaska.', 'answer': 'TRUE'},
    {'text': 'San Marino is the only country completely surrounded by another country.', 'answer': 'FALSE'},
    {'text': 'Steel is an alloy of Iron and Carbon.', 'answer': 'TRUE'},
    {'text': 'Norwegian producer Kygo released a remix of the song &quot;Sexual Healing&quot; by Marvin Gaye.', 'answer': 'TRUE'},
    {'text': 'Sargon II, a king of the Neo-Assyrian Empire, was a direct descendant of Sargon of Akkad.', 'answer': 'FALSE'},
    {'text': 'A universal set, or a set that contains all sets, exists.', 'answer': 'FALSE'},
    {'text': 'The sum of all the numbers on a roulette wheel is 666.', 'answer': 'TRUE'},
    {'text': 'Faust is a playable character in &quot;Guilty Gear Xrd Revelator&quot;.', 'answer': 'TRUE'},
    {'text': 'Ashley Frangipane performs under the stage name Halsey.', 'answer': 'TRUE'},
    {'text': 'Anatomy considers the forms of macroscopic structures such as organs and organ systems.', 'answer': 'TRUE'},
    {'text': 'Gothenburg is the capital of Sweden.', 'answer': 'FALSE'},
    {'text': 'Ottawa is the capital of Canada.', 'answer': 'TRUE'},
    {'text': 'Despite being seperated into multiple countries, The Scandinavian countries are unified by all having the same monarch.', 'answer': 'FALSE'},
    {'text': 'Russia passed a law in 2013 which outlaws telling children that homosexuals exist.', 'answer': 'TRUE'},
    {'text': 'In Undertale, having a &quot;Fun Value&quot; set to 56-57 will play the &quot;Wrong Number Song Call&quot;.', 'answer': 'FALSE'},
    {'text': 'In Team Fortress 2, being disguised as a scout or medic results in a speed boost.', 'answer': 'FALSE'},
    {'text': 'Centripedal force is an apparent force that acts outward on a body moving around a center, arising from the body&#039;s inertia.', 'answer': 'FALSE'},
    {'text': 'Abraham Lincoln was the first U.S. President to be born outside the borders of the thirteen original states. ', 'answer': 'TRUE'},
    {'text': 'When you cry in space, your tears stick to your face.', 'answer': 'TRUE'},
    {'text': 'The song &quot;Mystery Train&quot; was released by artist &quot;Little Junior&#039;s Blue Flames&quot; in 1953.', 'answer': 'TRUE'},
    {'text': 'Early RAM was directly seated onto the motherboard and could not be easily removed.', 'answer': 'TRUE'},
    {'text': 'The Battle of Trafalgar took place on October 23rd, 1805', 'answer': 'FALSE'},
    {'text': 'An exothermic reaction is a chemical reaction that releases energy by radiating electricity.', 'answer': 'FALSE'},
    {'text': 'E = MC3', 'answer': 'FALSE'},
    {'text': 'It&#039;s not possible to format a write-protected DVD-R Hard Disk.', 'answer': 'TRUE'},
    {'text': 'In Battlestar Galactica (2004), Cylons were created by man as cybernetic workers and soldiers.',
     'answer': 'TRUE'},
    {'text': 'In &quot;Star Trek&quot;, Klaang is a typical Klingon male.', 'answer': 'TRUE'},
    {'text': 'In &quot;JoJo&#039;s Bizarre Adventure&quot;, Father Enrico Pucchi uses a total of 3 stands in Part 6: Stone Ocean.', 'answer': 'TRUE'},
    {'text': 'In &quot;Starbound&quot;, the track played by the Decorated Music Box is named &quot;Atlas&quot;.', 'answer': 'TRUE'},
    {'text': 'In &quot;League of Legends&quot;, there exists four different types of Dragon.', 'answer': 'FALSE'},
    {'text': '&quot;Return to Castle Wolfenstein&quot; was the only game of the Wolfenstein series where you don&#039;t play as William &quot;B.J.&quot; Blazkowicz.', 'answer': 'FALSE'},
    {'text': 'You can square root a negative number with an imaginary number &quot;i&quot;.', 'answer': 'TRUE'},
    {'text': 'The United States of America was the first country to launch a man into space.', 'answer': 'FALSE'},
    {'text': 'Donald Duck played the role of Bob Cratchit in Disney&#039;s 1983 adaptation of A Christmas Carol.', 'answer': 'FALSE'},
    {'text': 'The most frequent subconscious activity repeated by the human body is blinking.', 'answer': 'FALSE'},
    {'text': 'In 2008, Usain Bolt set the world record for the 100 meters with one shoelace untied.', 'answer': 'TRUE'},
    {'text': 'The character Plum from &quot;No Game No Life&quot; is a girl.',
        'answer': 'FALSE'},
    {'text': 'Rabbits are carnivores.', 'answer': 'FALSE'},
    {'text': 'Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.', 'answer': 'TRUE'},
    {'text': 'The music group Daft Punk got their name from a negative review they recieved.', 'answer': 'TRUE'},
    {'text': 'There are no roads in/out of Juneau, Alaska.', 'answer': 'TRUE'},
    {'text': 'San Marino is the only country completely surrounded by another country.', 'answer': 'FALSE'},
    {'text': 'Steel is an alloy of Iron and Carbon.', 'answer': 'TRUE'},
    {'text': 'Norwegian producer Kygo released a remix of the song &quot;Sexual Healing&quot; by Marvin Gaye.', 'answer': 'TRUE'},
    {'text': 'Sargon II, a king of the Neo-Assyrian Empire, was a direct descendant of Sargon of Akkad.', 'answer': 'FALSE'},
    {'text': 'A universal set, or a set that contains all sets, exists.', 'answer': 'FALSE'},
    {'text': 'The sum of all the numbers on a roulette wheel is 666.', 'answer': 'TRUE'},
    {'text': 'Faust is a playable character in &quot;Guilty Gear Xrd Revelator&quot;.', 'answer': 'TRUE'},
    {'text': 'Ashley Frangipane performs under the stage name Halsey.', 'answer': 'TRUE'},
    {'text': 'Anatomy considers the forms of macroscopic structures such as organs and organ systems.', 'answer': 'TRUE'},
    {'text': 'Gothenburg is the capital of Sweden.', 'answer': 'FALSE'},
    {'text': 'Ottawa is the capital of Canada.', 'answer': 'TRUE'},
    {'text': 'Despite being seperated into multiple countries, The Scandinavian countries are unified by all having the same monarch.', 'answer': 'FALSE'},
    {'text': 'Russia passed a law in 2013 which outlaws telling children that homosexuals exist.', 'answer': 'TRUE'},
    {'text': 'In Undertale, having a &quot;Fun Value&quot; set to 56-57 will play the &quot;Wrong Number Song Call&quot;.', 'answer': 'FALSE'},
    {'text': 'In Team Fortress 2, being disguised as a scout or medic results in a speed boost.', 'answer': 'FALSE'},
    {'text': 'Centripedal force is an apparent force that acts outward on a body moving around a center, arising from the body&#039;s inertia.', 'answer': 'FALSE'},
    {'text': 'Abraham Lincoln was the first U.S. President to be born outside the borders of the thirteen original states. ', 'answer': 'TRUE'},
    {'text': 'When you cry in space, your tears stick to your face.', 'answer': 'TRUE'},
    {'text': 'The song &quot;Mystery Train&quot; was released by artist &quot;Little Junior&#039;s Blue Flames&quot; in 1953.', 'answer': 'TRUE'},
    {'text': 'Early RAM was directly seated onto the motherboard and could not be easily removed.', 'answer': 'TRUE'},
    {'text': 'The Battle of Trafalgar took place on October 23rd, 1805', 'answer': 'FALSE'},
    {'text': 'An exothermic reaction is a chemical reaction that releases energy by radiating electricity.', 'answer': 'FALSE'},
    {'text': 'E = MC3', 'answer': 'FALSE'},
    {'text': 'It&#039;s not possible to format a write-protected DVD-R Hard Disk.', 'answer': 'TRUE'},
    {'text': 'In Battlestar Galactica (2004), Cylons were created by man as cybernetic workers and soldiers.',
     'answer': 'TRUE'},
    {'text': 'In &quot;Star Trek&quot;, Klaang is a typical Klingon male.', 'answer': 'TRUE'},
    {'text': 'In &quot;JoJo&#039;s Bizarre Adventure&quot;, Father Enrico Pucchi uses a total of 3 stands in Part 6: Stone Ocean.', 'answer': 'TRUE'},
    {'text': 'In &quot;Starbound&quot;, the track played by the Decorated Music Box is named &quot;Atlas&quot;.', 'answer': 'TRUE'},
    {'text': 'In &quot;League of Legends&quot;, there exists four different types of Dragon.', 'answer': 'FALSE'},
    {'text': '&quot;Return to Castle Wolfenstein&quot; was the only game of the Wolfenstein series where you don&#039;t play as William &quot;B.J.&quot; Blazkowicz.', 'answer': 'FALSE'},
    {'text': 'You can square root a negative number with an imaginary number &quot;i&quot;.', 'answer': 'TRUE'},
    {'text': 'The United States of America was the first country to launch a man into space.', 'answer': 'FALSE'},
    {'text': 'Donald Duck played the role of Bob Cratchit in Disney&#039;s 1983 adaptation of A Christmas Carol.', 'answer': 'FALSE'},
    {'text': 'The most frequent subconscious activity repeated by the human body is blinking.', 'answer': 'FALSE'},
    {'text': 'In 2008, Usain Bolt set the world record for the 100 meters with one shoelace untied.', 'answer': 'TRUE'},
    {'text': 'The character Plum from &quot;No Game No Life&quot; is a girl.',
        'answer': 'FALSE'},
    {'text': 'Rabbits are carnivores.', 'answer': 'FALSE'},
    {'text': 'Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.', 'answer': 'TRUE'},
    {'text': 'The music group Daft Punk got their name from a negative review they recieved.', 'answer': 'TRUE'},
    {'text': 'There are no roads in/out of Juneau, Alaska.', 'answer': 'TRUE'},
    {'text': 'San Marino is the only country completely surrounded by another country.', 'answer': 'FALSE'},
    {'text': 'Steel is an alloy of Iron and Carbon.', 'answer': 'TRUE'},
    {'text': 'Norwegian producer Kygo released a remix of the song &quot;Sexual Healing&quot; by Marvin Gaye.', 'answer': 'TRUE'},
    {'text': 'Sargon II, a king of the Neo-Assyrian Empire, was a direct descendant of Sargon of Akkad.', 'answer': 'FALSE'},
    {'text': 'A universal set, or a set that contains all sets, exists.', 'answer': 'FALSE'},
    {'text': 'The sum of all the numbers on a roulette wheel is 666.', 'answer': 'TRUE'},
    {'text': 'Faust is a playable character in &quot;Guilty Gear Xrd Revelator&quot;.', 'answer': 'TRUE'},
    {'text': 'Ashley Frangipane performs under the stage name Halsey.', 'answer': 'TRUE'},
    {'text': 'Anatomy considers the forms of macroscopic structures such as organs and organ systems.', 'answer': 'TRUE'},
    {'text': 'Gothenburg is the capital of Sweden.', 'answer': 'FALSE'},
    {'text': 'Ottawa is the capital of Canada.', 'answer': 'TRUE'},
    {'text': 'Despite being seperated into multiple countries, The Scandinavian countries are unified by all having the same monarch.', 'answer': 'FALSE'},
    {'text': 'Russia passed a law in 2013 which outlaws telling children that homosexuals exist.', 'answer': 'TRUE'},
    {'text': 'In Undertale, having a &quot;Fun Value&quot; set to 56-57 will play the &quot;Wrong Number Song Call&quot;.', 'answer': 'FALSE'},
    {'text': 'In Team Fortress 2, being disguised as a scout or medic results in a speed boost.', 'answer': 'FALSE'},
    {'text': 'Centripedal force is an apparent force that acts outward on a body moving around a center, arising from the body&#039;s inertia.', 'answer': 'FALSE'},
    {'text': 'Abraham Lincoln was the first U.S. President to be born outside the borders of the thirteen original states. ', 'answer': 'TRUE'},
    {'text': 'When you cry in space, your tears stick to your face.', 'answer': 'TRUE'},
    {'text': 'The song &quot;Mystery Train&quot; was released by artist &quot;Little Junior&#039;s Blue Flames&quot; in 1953.', 'answer': 'TRUE'},
    {'text': 'Early RAM was directly seated onto the motherboard and could not be easily removed.', 'answer': 'TRUE'},
    {'text': 'The Battle of Trafalgar took place on October 23rd, 1805', 'answer': 'FALSE'},
    {'text': 'An exothermic reaction is a chemical reaction that releases energy by radiating electricity.', 'answer': 'FALSE'},
    {'text': 'E = MC3', 'answer': 'FALSE'},
    {'text': 'It&#039;s not possible to format a write-protected DVD-R Hard Disk.', 'answer': 'TRUE'},
    {'text': 'In Battlestar Galactica (2004), Cylons were created by man as cybernetic workers and soldiers.',
     'answer': 'TRUE'},
    {'text': 'In &quot;Star Trek&quot;, Klaang is a typical Klingon male.', 'answer': 'TRUE'},
    {'text': 'In &quot;JoJo&#039;s Bizarre Adventure&quot;, Father Enrico Pucchi uses a total of 3 stands in Part 6: Stone Ocean.', 'answer': 'TRUE'},
    {'text': 'In &quot;Starbound&quot;, the track played by the Decorated Music Box is named &quot;Atlas&quot;.', 'answer': 'TRUE'},
    {'text': 'In &quot;League of Legends&quot;, there exists four different types of Dragon.', 'answer': 'FALSE'},
    {'text': '&quot;Return to Castle Wolfenstein&quot; was the only game of the Wolfenstein series where you don&#039;t play as William &quot;B.J.&quot; Blazkowicz.', 'answer': 'FALSE'},
    {'text': 'You can square root a negative number with an imaginary number &quot;i&quot;.', 'answer': 'TRUE'},
    {'text': 'The United States of America was the first country to launch a man into space.', 'answer': 'FALSE'},
    {'text': 'Donald Duck played the role of Bob Cratchit in Disney&#039;s 1983 adaptation of A Christmas Carol.', 'answer': 'FALSE'},
    {'text': 'The most frequent subconscious activity repeated by the human body is blinking.', 'answer': 'FALSE'},
    {'text': 'In 2008, Usain Bolt set the world record for the 100 meters with one shoelace untied.', 'answer': 'TRUE'},
    {'text': 'The character Plum from &quot;No Game No Life&quot; is a girl.',
        'answer': 'FALSE'},
    {'text': 'Rabbits are carnivores.', 'answer': 'FALSE'},
    {'text': 'Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.', 'answer': 'TRUE'}
]
